using RecipeApp.API.DTOs.MealPlans;
using RecipeApp.API.DTOs.ShoppingLists;
using RecipeApp.Tests.Helpers;
using RecipeApp.Tests.Infrastructure;
using System.Net;
using System.Net.Http.Json;

namespace RecipeApp.Tests.Endpoints;

[Collection("Database")]
public class ShoppingListEndpointsTests(DatabaseFixture db) : IAsyncLifetime
{
    public ValueTask InitializeAsync() => db.TruncateAllAsync();
    public ValueTask DisposeAsync() => ValueTask.CompletedTask;

    private HttpClient Client => db.CreateClient();

    private async Task<Guid> SeedIngredientAsync(string name = "flour", string displayName = "Flour")
    {
        await using var ctx = db.CreateDbContext();
        var ing = TestDataBuilder.Ingredient(name, displayName);
        ctx.Ingredients.Add(ing);
        await ctx.SaveChangesAsync();
        return ing.Id;
    }

    private async Task<Guid> SeedRecipeAsync(Guid ingredientId, string name = "Test Recipe")
    {
        var request  = TestDataBuilder.CreateRecipeRequest(ingredientId, name);
        var response = await Client.PostAsJsonAsync("/api/v1/recipes", request);
        response.EnsureSuccessStatusCode();
        var recipe = await response.Content.ReadFromJsonAsync<API.DTOs.Recipes.RecipeDetailResponse>();
        return recipe!.Id;
    }

    private async Task<MealPlanDetailResponse> CreatePlanViaApi(string name = "Plan")
    {
        var response = await Client.PostAsJsonAsync("/api/v1/meal-plans", new { name });
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<MealPlanDetailResponse>())!;
    }

    private async Task AddRecipeToPlanAsync(Guid planId, Guid recipeId)
    {
        var response = await Client.PostAsJsonAsync($"/api/v1/meal-plans/{planId}/recipes", new { recipeId });
        response.EnsureSuccessStatusCode();
    }

    // ── GET /shopping-lists/active ────────────────────────────────────────────

    [Fact]
    public async Task GetActive_NoActivePlan_Returns404()
    {
        var response = await Client.GetAsync("/api/v1/shopping-lists/active");
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task GetActive_WithActivePlanAndRecipes_Returns200AutoGenerated()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        var response = await Client.GetAsync("/api/v1/shopping-lists/active");
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        var list = await response.Content.ReadFromJsonAsync<ShoppingListResponse>();
        list.Should().NotBeNull();
        list!.Items.Should().NotBeEmpty();
        list.MealPlanId.Should().Be(plan.Id);
    }

    [Fact]
    public async Task GetActive_ReturnsIsStaleTrue_WhenPlanChangedAfterGeneration()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        // Generate list
        var firstResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        firstResponse.EnsureSuccessStatusCode();

        await Task.Delay(20);

        // Mutate the plan (add another recipe)
        var recipeId2 = await SeedRecipeAsync(ingId, "R2");
        await AddRecipeToPlanAsync(plan.Id, recipeId2);

        var staleResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var staleList = await staleResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();
        staleList!.IsStale.Should().BeTrue();
    }

    // ── POST /shopping-lists/active/generate ──────────────────────────────────

    [Fact]
    public async Task Regenerate_NoActivePlan_Returns404()
    {
        var response = await Client.PostAsync("/api/v1/shopping-lists/active/generate", null);
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task Regenerate_PreservesCustomItems()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        // Auto-generate first
        var listResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var list = await listResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();

        // Add custom item
        await Client.PostAsJsonAsync($"/api/v1/shopping-lists/{list!.Id}/items",
            new { name = "CustomBread", amount = (decimal?)null, unit = (string?)null, category = "OTHER" });

        // Regenerate
        var regenResponse = await Client.PostAsync("/api/v1/shopping-lists/active/generate", null);
        regenResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        var regenerated = await regenResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();

        regenerated!.Items.Should().Contain(i => i.IsCustom && i.DisplayName == "CustomBread");
    }

    // ── POST /shopping-lists/{id}/items ──────────────────────────────────────

    [Fact]
    public async Task AddCustomItem_Valid_Returns201WithLocation()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        var listResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var list = await listResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();

        var response = await Client.PostAsJsonAsync($"/api/v1/shopping-lists/{list!.Id}/items",
            new { name = "Eggs", amount = 6m, unit = "pcs", category = "DAIRY" });

        response.StatusCode.Should().Be(HttpStatusCode.Created);
        response.Headers.Location.Should().NotBeNull();

        var item = await response.Content.ReadFromJsonAsync<ShoppingListItemResponse>();
        item!.DisplayName.Should().Be("Eggs");
        item.IsCustom.Should().BeTrue();
    }

    [Fact]
    public async Task AddCustomItem_EmptyName_Returns400()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        var listResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var list = await listResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();

        var response = await Client.PostAsJsonAsync($"/api/v1/shopping-lists/{list!.Id}/items",
            new { name = "", amount = (decimal?)null, unit = (string?)null, category = (string?)null });

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    [Fact]
    public async Task AddCustomItem_UnknownList_Returns404()
    {
        var response = await Client.PostAsJsonAsync($"/api/v1/shopping-lists/{Guid.NewGuid()}/items",
            new { name = "X", amount = (decimal?)null, unit = (string?)null, category = (string?)null });
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    // ── PUT /shopping-lists/{id}/items/{itemId} ───────────────────────────────

    [Fact]
    public async Task UpdateItem_ToggleChecked_Returns200()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        var listResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var list = await listResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();
        var item = list!.Items[0];

        var response = await Client.PutAsJsonAsync(
            $"/api/v1/shopping-lists/{list.Id}/items/{item.Id}",
            new { isChecked = true, amount = item.Amount, unit = item.Unit });

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var updated = await response.Content.ReadFromJsonAsync<ShoppingListItemResponse>();
        updated!.IsChecked.Should().BeTrue();
    }

    [Fact]
    public async Task UpdateItem_WrongList_Returns404()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        var listResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var list = await listResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();

        var response = await Client.PutAsJsonAsync(
            $"/api/v1/shopping-lists/{Guid.NewGuid()}/items/{list!.Items[0].Id}",
            new { isChecked = true, amount = (decimal?)null, unit = (string?)null });

        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    // ── DELETE /shopping-lists/{id}/items/{itemId} ────────────────────────────

    [Fact]
    public async Task DeleteCustomItem_Returns204()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        var listResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var list = await listResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();

        var addResponse = await Client.PostAsJsonAsync($"/api/v1/shopping-lists/{list!.Id}/items",
            new { name = "Custom", amount = (decimal?)null, unit = (string?)null, category = (string?)null });
        var customItem = await addResponse.Content.ReadFromJsonAsync<ShoppingListItemResponse>();

        var response = await Client.DeleteAsync($"/api/v1/shopping-lists/{list.Id}/items/{customItem!.Id}");
        response.StatusCode.Should().Be(HttpStatusCode.NoContent);
    }

    [Fact]
    public async Task DeleteRecipeDerivedItem_Returns409()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        var listResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var list = await listResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();
        var recipeItem = list!.Items.First(i => !i.IsCustom);

        var response = await Client.DeleteAsync($"/api/v1/shopping-lists/{list.Id}/items/{recipeItem.Id}");
        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    [Fact]
    public async Task DeleteItem_WrongList_Returns404()
    {
        var ingId    = await SeedIngredientAsync();
        var recipeId = await SeedRecipeAsync(ingId);
        var plan     = await CreatePlanViaApi();
        await AddRecipeToPlanAsync(plan.Id, recipeId);

        var listResponse = await Client.GetAsync("/api/v1/shopping-lists/active");
        var list = await listResponse.Content.ReadFromJsonAsync<ShoppingListResponse>();
        var addResponse = await Client.PostAsJsonAsync($"/api/v1/shopping-lists/{list!.Id}/items",
            new { name = "X", amount = (decimal?)null, unit = (string?)null, category = (string?)null });
        var customItem = await addResponse.Content.ReadFromJsonAsync<ShoppingListItemResponse>();

        var response = await Client.DeleteAsync($"/api/v1/shopping-lists/{Guid.NewGuid()}/items/{customItem!.Id}");
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }
}
